import type { Metadata } from 'next';
import { Space_Mono } from 'next/font/google';
import './globals.css';
import '@radix-ui/themes/styles.css';

import { Theme } from '@radix-ui/themes';

const space = Space_Mono({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={space.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
